<?php

/**
 * @file
 *
 * Un module de gestion de stages GAIA
 * des tables supplementaires sont ajoutees a la base de donnees Drupal
 * - les tables issues de GAIA, préfixées par gbb (gbb_gdisp, gbb_gmodu, gbb_gdire...)
 * - les tables propres au module (gbb_file, gbb_session...)
 */

/**
* Implement hook_views_api().
*
* Charge le hook_views_data du fichier gbb.views.inc
*/
function gbb_views_api() {
      return array('api' => 3.0);
}

/**
* Implements hook_permission().
*
* Les accès aux pages définies par le module sont régis par des permissions 
* spéciales définies ici.
* Ces permissions pourront être attribuées à des rôles dans l'interface de gestion DRUPAL.
*/

function gbb_permission() {
  return array(
    'stable gbb' => array(
      'title' => t('Accéder à GaiaBB'), 
      'description' => t('Donne acèès aux fonctionnalités en production du tableau de bord GaiaBB.'),
      ),
    'testing gbb' => array(
      'title' => t('TESTING'), 
      'description' => t('Donne accès aux fonctionnalités qui n\'ont pas encore été acceptés 
                          dans la version en production, mais qui sont en attente de l\'être.'),
      ),
    'unstable gbb' => array(
      'title' => t('UNSTABLE'), 
      'description' => t('Donne accès aux fonctionnalités instables en cours de développement.'),
      ),
    'gest_sessions gbb' => array(
      'title' => t('Gérer les demandes d\'ajout de sessions GAIA pour un module'), 
      'description' => t('Autorise à jouter, modifier, dupliquer ou supprimer des sessions.'),
      ),
    'gest_convocs gbb' => array(
      'title' => t('Signaler les envois/impressions de convocations'), 
      'description' => t('Autorise à marquer comme imprimées ou envoyées les convocations.'),
      ),
    'gest_etablissements gbb' => array(
      'title' => t('Ajouter un établissement dans la base de données'), 
      'description' => t('Permet de modifier le RNE (l\'identifiant), le nom et le sigle. 
                          Les autres données sont modifiables par tous.'),
      ),
  );
}

/**
 * Implements hook_menu
 */

function gbb_menu() {

  $items = array();

  // Etant donnés une année (09,10,11,12,...), un co_degré (1 ou 2) et un co_tres (1,2 ou 3)
  // affichage de la liste des responsables des stages
  //   exemple : liste_stages/12/2/1
  // affichage de la liste des stages pour un conseiller (DENISE ou ARGO) donné
  //   exemple : liste_stages/12/2/1/DENISE

  $items['liste'] = array(
        'title' => '',
        'page callback' => 'gbb_liste_view',
        'access arguments' => array('stable gbb'),
        'type' => MENU_CALLBACK,
  );

  // Etant donné un co_degré (1 ou 2)
  // Affiche la page de gestion du module co_modu
  //   exemple : module/2/26142

  $items['module'] = array(
        'title' => '',
        'page callback' => 'gbb_module_view',
        'access arguments' => array('stable gbb'),
        'type' => MENU_CALLBACK,
  );

  // Etant donné un id (112 ou 2222)
  // Affiche la page de gestion des formateurs
  //   exemple : formateur/112

  $items['formateur'] = array(
        'title' => '',
        'page callback' => 'gbb_formateur_view',
        'access arguments' => array('stable gbb'),
        'type' => MENU_CALLBACK,
  );

  // Etant donné un id (112 ou 2222)
  // Affiche la page de gestion des établisssemnets
  //   exemple : etablissement/112

  $items['etablissement'] = array(
        'title' => '',
        'page callback' => 'gbb_etablissement_view',
        'access arguments' => array('stable gbb'),
        'type' => MENU_CALLBACK,
  );

  // Pages pour autocomplete AJAX
  // TODO : décrire
  $items['autocomp/etablissement'] = array(
        'page callback' => '_gbb_autocompetab',
        'access arguments' => array('access gbb'),
        'type' => MENU_CALLBACK
  );
  // TODO : décrire
  $items['autocomp/formateur'] = array(
        'page callback' => '_gbb_autocompform',
        'access arguments' => array('access gbb'),
        'type' => MENU_CALLBACK
  );
  // TODO : décrire
  $items['autocomp/formateur2'] = array(
        'page callback' => '_gbb_autocompform2',
        'access arguments' => array('access gbb'),
        'type' => MENU_CALLBACK
  );
  // TODO : décrire
  $items['autocomp/responsable'] = array(
        'page callback' => '_gbb_autocompresp',
        'access arguments' => array('access gbb'),
        'type' => MENU_CALLBACK
  );
  // TODO : décrire
  $items['autocomp/stage'] = array(
        'page callback' => '_gbb_autocompstage',
        'access arguments' => array('access gbb'),
        'type' => MENU_CALLBACK
  );

  return $items;

}

variable_set('_gbb_session_alert_icon', array(
  'path' => drupal_get_path('module', 'gbb') . '/images/flag_red.png',
  'alt' => 'session_alert',
  'title' => t('Alerte sur session : le service administratif est prévenu d\'un changement important.'),
  'attributes' => array('class' => 'some-img', 'id' => 'my-img'))
);
variable_set('_gbb_not_en_attente_icon', array(
  'path' => drupal_get_path('module', 'gbb') . '/images/control_play_blue.png',
  'alt' => 'en attente',
  'title' => t('Demande de préparation des convocations.'),
  'attributes' => array('class' => 'some-img', 'id' => 'my-img'))
);
variable_set('_gbb_en_attente_icon', array(
  'path' => drupal_get_path('module', 'gbb') . '/images/control_pause.png',
  'alt' => 'en attente',
  'title' => t('En attente : ne pas préparer les convocations pour le moment.'),
  'attributes' => array('class' => 'some-img', 'id' => 'my-img'))
);
variable_set('_gbb_convoc_sent_icon', array(
  'path' => drupal_get_path('module', 'gbb') . '/images/convoc_sent.png',
  'alt' => 'Convoc envoyée',
  'title' => t('La convocation pour cette session a été envoyée.'),
  'attributes' => array('class' => 'some-img', 'id' => 'my-img'))
);
variable_set('_gbb_user_edit_icon', array(
  'path' => drupal_get_path('module', 'gbb') . '/images/user_edit.png',
  'alt' => 'user_edit',
  'title' => t('Voir la fiche.'),
  'attributes' => array('class' => 'some-img', 'id' => 'my-img'))
);
variable_set('_gbb_etab_edit_icon', array(
  'path' => drupal_get_path('module', 'gbb') . '/images/building.png',
  'alt' => 'etab_edit',
  'title' => t('Voir la fiche.'),
  'attributes' => array('class' => 'some-img', 'id' => 'my-img'))
);


//module_load_include('inc', 'gbb', 'gbb_liste');
module_load_include('inc', 'gbb', 'gbb_module');
module_load_include('inc', 'gbb', 'gbb_formateur');
module_load_include('inc', 'gbb', 'gbb_etablisement');
//module_load_include('inc', 'gbb', 'gbb_evaluation');

